title:              Foundation-Jekyll

# Versioning
current_version: 1.2.0
foundation-version: 6.0.0

author:
  name:             Aaron K. White
  email:            aaron@aaronkwhite.com
  url:              http://aaronkwhite.com
  github:           aaronkwhite
  twitter:          aaronkwhite
  twitter_url:      http://twitter.com/aaronkwhite


# Dependencies
markdown:           kramdown
highlighter:        pygments

# Permalinks
permalink:          pretty
#relative_permalinks: true

# Server
source:             ./
destination:        ./_site

port:               9002
baseurl:            ""
url:                http://foundationjekyll.com

# exclude this stuff when building the static site
exclude:            ["sass","scss",".gitignore","README.md","config.codekit"]


## CUSTOM VARS

ga_id:              UA-58024365-1
site_name:          Foundation-Jekyll
site_description :  A bare bones Foundation & Jekyll boilerplate to get up and running fast.
site_copyright:     Copyright (c) 2014 @aaronkwhite
site_license:       http://opensource.org/licenses/MIT
site_url:           http://foundationjekyll.com
site_email:         info@foundationjekyll.com
site_phone:         (555) 555-1234
site_jekyll:        http://jekyllrb.com
site_foundation:    http://foundation.zurb.com
site_github_url:    http://github.com/aaronkwhite/foundation-jekyll
site_github_zip:    http://github.com/aaronkwhite/foundation-jekyll/archive/master.zip



# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/stylesheets
  style:            :compressed
