title:              Foundation-Jekyll

# Versioning
current_version: 1.0.2

author:
  name:             Aaron K. White
  email:            aaron@aaronkwhite.com
  github:           aaronkwhite
  twitter:          aaronkwhite

# Dependencies
markdown:           kramdown
highlighter:        pygments

# Permalinks
permalink:          pretty
#relative_permalinks: true

# Server
source:             ./source
destination:        ./_site

port:               9002
baseurl:            ""
url:                http://yoururl.com

# exclude this stuff when building the static site
exclude:            ["sass","scss",".gitignore","README.md","config.codekit"]


## CUSTOM VARS

#ga_id:             ##-########-###
site_name:          Foundation-Jekyll 
site_description :  Bare Bones Foundation-Bootstrap starting point
site_copyright:     Copyright (c) 2014 @aaronkwhite
site_url:           http://yoururl.com
site_email:         site@domain.com
site_phone:         (555) 555-1234 



# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
